#!/usr/bin/env bash

# Check if required tools are installed
if ! command -v wal &> /dev/null; then
    zenity --error --text="Pywal (wal) is not installed!\nInstall with: sudo pacman -S pywal  # or your distro's package"
    exit 1
fi

if ! command -v zenity &> /dev/null; then
    echo "Zenity is required for file selection. Install zenity first."
    exit 1
fi

# Select wallpaper through GUI
WALLPAPER=$(zenity --file-selection \
    --title="Select Wallpaper" \
    --file-filter="Image files | *.jpg *.jpeg *.png *.webp")

# Exit if user canceled
if [ -z "$WALLPAPER" ]; then
    exit 0
fi

# Generate color scheme
wal -n -i "$WALLPAPER"

# Create Hyprland config
HYPR_CONF="$HOME/.config/hypr/colors.conf"

cat > "$HYPR_CONF" <<EOL
# Generated by Pywal-Hyprland Script
\$wallpaper = $WALLPAPER

# Special Colors
\$background = $(cat "$HOME/.cache/wal/colors.json" | jq -r '.special.background')
\$foreground = $(cat "$HOME/.cache/wal/colors.json" | jq -r '.special.foreground')
\$cursor = $(cat "$HOME/.cache/wal/colors.json" | jq -r '.special.cursor')

# Color Palette
EOL

# Add color variables (color0-color15)
for i in {0..15}; do
    echo "\$color$i = $(cat "$HOME/.cache/wal/colors.json" | jq -r ".colors.color$i")" >> "$HYPR_CONF"
done

# Notification
if command -v notify-send &> /dev/null; then
    notify-send "Hyprland Colors Generated" "New scheme applied from $WALLPAPER"
else
    zenity --info --text="Hyprland color scheme generated!\n$HYPR_CONF"
fi

# Reload Hyprland (uncomment if needed)
# hyprctl reload
