#!/usr/bin/env bash

WALLPAPER_DIR="${HOME}/.config/wallpapers"
CONFIG_FILE="${HOME}/.config/hypr/hyprpaper.conf"

# Create wallpaper dir if it doesn't exist
mkdir -p "$WALLPAPER_DIR"

# Find all wallpapers
mapfile -t wallpapers < <(find -L "$WALLPAPER_DIR" -type f \( -iname "*.webp" -o -iname '*.jpg' -o -iname '*.png' -o -iname '*.jpeg' \))

if [[ ${#wallpapers[@]} -eq 0 ]]; then
    echo "No wallpapers found in $WALLPAPER_DIR"
    exit 1
fi

# Pick a random one
random_wall="${wallpapers[RANDOM % ${#wallpapers[@]}]}"

# Get active monitor names
mapfile -t monitors < <(hyprctl monitors | grep Monitor | awk '{print $2}')

# Regenerate hyprpaper.conf
{
    echo "# Auto-generated by change_wallpaper.sh"
    echo "preload = $random_wall"
    for mon in "${monitors[@]}"; do
        echo "wallpaper = $mon,$random_wall"
    done
} > "$CONFIG_FILE"

# Restart hyprpaper to apply new config
pkill -x hyprpaper
hyprpaper &

echo "Updated hyprpaper.conf with $random_wall for ${#monitors[@]} monitor(s)"
